apiVersion: v1
kind: Service
metadata:
  name: oraclequoteproject-service
  labels:
    app: oraclequoteproject
spec:
  selector:
    app: oraclequoteproject
  type: NodePort
  ports:
    - port: 3003
      nodePort: 32641
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraclequoteproject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oraclequoteproject
  template:
    metadata:
      labels:
        app: oraclequoteproject
    spec:
      containers:
        - name: oraclequoteproject
          image: iad.ocir.io/idavixsf5sbx/cristianohoshikawa/oraclequoteproject:latest
          ports:
            - containerPort: 3003
      imagePullSecrets:
        # enter the name of the secret you created
        - name: ocirsecret
