apiVersion: v1
kind: Service
metadata:
  name: consultacep-service
  labels:
    app: consultacep
spec:
  selector:
    app: consultacep
  type: NodePort
  ports:
    - port: 3003
      nodePort: 32641
---
apiVersion: apps/v1
kind: Deployment
metadata:
  #Canarian OK POD
  name: consultacep-deployment
  #Canarian NOK POD
  #name: consultacep-deployment-nok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultacep
  template:
    metadata:
      labels:
        app: consultacep
        version: ok
        #version: nok
    spec:
      containers:
        - name: consultacep
          #Canarina Deployment OK
          image: iad.ocir.io/idavixsf5sbx/cristianohoshikawa/consultacep:latest
          #Canarina Deployment NOK
          #image: iad.ocir.io/idavixsf5sbx/cristianohoshikawa/consultacepnok:latest
          ports:
            - containerPort: 3003
      imagePullSecrets:
        # enter the name of the secret you created
        - name: ocirsecret
---
kind: DestinationRule       # Defining which pods should be part of each subset
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: grouping-rules-for-consultacep
  namespace: default
spec:
  host: consultacep-service # Service
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 3
      interval: 20s
      baseEjectionTime: 30s
      maxEjectionPercent: 10
  subsets:
    - labels:   # SELECTOR.
        version: ok # find pods with label "safe"
      name: ok-group
    - labels:
        version: nok
      name: nok-group